openapi: 3.0.1
info:
  title: API Disney
  version: 1.0.0
servers:
  - url: "http://localhost:3000"
    description: Local Server

tags:
  - name: User
    description: User handler
  - name: Film
    description: Film handler
  - name: Character
    description: Character handler

paths:

  /users/signup:
    post:
      tags:
        - User
      summary: Signup
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BodySignupPost"
        required: true
      responses:
        200:
          description: The user was created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: User token
                    example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiJGdzZRbXc1WUZ6UXhWenJKcmVHSCIsImV4cCI6MTYzMTI4MjM2OH0.-T2ofAXiYNsHFmS3QTod8FjArlbSo8-A5snx_4rH3lE
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/ServerError"
        535:
          $ref: "#/components/responses/EmailError"


  /users/login:
    post:
      tags:
        - User
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BodyLoginPost"
        required: true
      responses:
        200:
          description: The user was logged successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: User token
                    example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiJGdzZRbXc1WUZ6UXhWenJKcmVHSCIsImV4cCI6MTYzMTI4MjM2OH0.-T2ofAXiYNsHFmS3QTod8FjArlbSo8-A5snx_4rH3lE

        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/ServerError"

  /movies/add:
    post:
      tags:
        - Film
      summary: Create film
      security:
        - userToken: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/BodyCreateFilmPost"
            encoding: 
                image: 
                  contentType: image/png, image/jpeg, image/jpg
        required: true
      responses:
        200:
          description: The film was created successfully
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/ServerError"
          
  /movies/:
    get:
      tags:
        - Film
      summary: Get films
      security:
        - userToken: []
      parameters:
      - name: name
        in: query
        required: false
        description: Nombre de la película o serie
        example: Star Wars Episode III Revenge of the Sith
        schema:
          type: string
      - name: genre
        in: query
        required: false
        description: Género de la película o serie
        example: 1
        schema:
          type: string
      - name: order
        in: query
        required: false
        description: Orden para mostrar los datos según fecha de creación
        example: ASC
        schema:
          type: string
      responses:
        200:
          description: (OK) Películas y series obtenidas con écito
          content:
            image/png:
              schema:
                type: string
                format: binary
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/ServerError"
  


components:
  securitySchemes:
    userToken:
      type: http
      scheme: bearer
      description: To obtain the token please login

  responses:
    Unauthorized:
      description: Unauthorized user

    NotFound:
      description: Data not found

    BadRequest:
      description: Error in data type or incomplete required fields

    ServerError:
      description: Internal server error

    EmailError:
      description: Error sending email
    


  schemas:
    BodySignupPost:
      type: object
      required:
        - name
        - surname
        - mail
        - password
      properties:
        name:
          type: string
          maximum: 50
          minimum: 3
          example: Agustina
        surname:
          type: string
          example: García Rey
        mail:
          type: string
          example: agus.garciarey@gmail.com
        password:
          type: string
          example: Disney123

    BodyLoginPost:
      type: object
      required:
        - mail
        - password
      properties:
        mail:
          type: string
          example: agus.garciarey@gmail.com
        password:
          type: string
          example: Disney123
  
    BodyCreateFilmPost:
      type: object
      required:
        - title
        - image
        - year
        - rating
        - genreId
        - characters
      properties:
        title:
          type: string
          maximum: 80
          example: Star Wars Episode III Revenge of the Sith
        image:
            type: string
            format: binary
        year:
          type: number
          example: 2005
        rating:
          type: number
          example: 4.7
        genreId:
          type: number
          description: 1.Ciencia ficción 2.Drama 3.Comedia
          example: 1
        characters:
          type: array
          description: Enter characters already created. If they still do not exist, leave this field empty.
          items:
            type: object
            required:
              - name
            properties:
              name:
                type: string
          example:
            - name: Anakin Skywalker
            - name: Chewbacca
            
    ResponseGetFilm:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        image:
          type: string
          format: binary
        family:
          type: number
        year:
          type: number
        rating:
          type: number
        genre:
          type: string
        created_at:
          type: number
        updated_at:
          type: number
          
    ResponseGetFilms:
      type: array
      items:
          $ref: '#/components/schemas/ResponseGetFilm'
          